services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    command: make dev
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app